---
- name: check Checkpoint sms
  hosts: cpsms
  connection: httpapi
  gather_facts: no
  collections:
  - check_point.mgmt
  tasks:
  - name: show-gateways-and-servers
    cp_mgmt_show_gateways_and_servers:
      details_level: full
