
- name: check GAiA gateway
  hosts: cpgws
  connection: httpapi
  gather_facts: no
  collections:
    - check_point.gaia

  tasks:
    - name: Show api versions
      check_point.gaia.cp_gaia_api_versions_facts:
