---
- name: check Checkpoint sms
  hosts: cpsms
  connection: httpapi
  gather_facts: no
  collections:
  - check_point.mgmt
  tasks:
  - name: show-checkpoint-host
    cp_mgmt_checkpoint_host_facts:
