---
- name: check Checkpoint sms
  hosts: cpsms
  connection: httpapi
  gather_facts: no
  collections:
  - check_point.mgmt
  tasks:  
  - name: Show api versions
    check_point.gaia.cp_gaia_api_versions_facts:
  - name: show-checkpoint-host
    cp_mgmt_checkpoint_host_facts:
  - name: show-gateways-and-servers
    cp_mgmt_show_gateways_and_servers:
      details_level: full
  - name: show-updatable-object
    cp_mgmt_updatable_object_facts:
