
- name: Configure GAiA gateway
  hosts: cpgws
  connection: httpapi
  gather_facts: no
  collections:
    - check_point.gaia

  tasks:
    - name: Set login banner
      cp_gaia_banner:
        banner_message: "Authorized access only."
