- name: Check Check Point Gateway Data
  hosts: checkpoint_test
  gather_facts: no
  collections:
    - check_point.gaia

  tasks:
    - name: Show current DNS configuration
      check_point.gaia.cp_gaia_dns_facts:
      
    - name: Display DNS settings
      debug:
        var: ansible_facts.cp_gaia_dns

